### ISSUE TITLE
PX4ECL EKF

### ISSUE THREAD

**Issue by ybabs** [alexandreguerradeoliveira/drone_EKF#1]
Hi, I've been looking for a lightweight version of the PX4 ECL EKF. Looking at the readme, I just wanted to confirm if this is based on the [PX4 ECL EKF](https://github.com/PX4/PX4-ECL)?

**Comment by alexandreguerradeoliveira** [comment]
Hi!
Its based on the Px4 Ecl EKF in the sense that it also uses a EKF with the same predition and sensor measurement dynamical models.
The code itself is not taken from the px4 ecl, and the EKF does not include the output filter that is present on the px4 ekf.

**Comment by ybabs** [comment]
Thanks for the clarification,  sorry one more question, what's the difference between `ekf_from_matlab` and `ekf_from_matlab_alone`?

**Comment by alexandreguerradeoliveira** [comment]
These are the exported C version of the MATLAB libraries.

I was testing the EKF on a self build PCB with multiple devices. If I remember correctly both folders should contain an arduino project (.ino) and the one in ekf_from_matlab_alone uses only the devices needed to get the EKF runing while the one in ekf_from_matlab might have some simple telemetry code I used to send the real-time EKF data to the computer using a Xbee radio.
